on:
  push:
    tags:
      - "aur/*"

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arjix-aur/runner-image-arch:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: build packages
        run: |
          cp build.sh /home/docker
          cd /home/docker
          runuser -u docker ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "/home/docker/*.pkg.tar.zst"
          fail_on_unmatched_files: true
